#######################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################


spring:
  output:
    ansi:
      enabled: ALWAYS
  neo4j:
    uri: bolt://db:7687
    authentication:
      username: neo4j
      password: secret
  data:
    neo4j:
      database: neo4j
